// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import { requireUserSession } from "@/hooks/user";
import { cn } from "@/lib/utils";

export default async function ProtectedLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await requireUserSession();
  return (
    <html lang="en">
      <body
        className={cn(
          " bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-sky-400 to-blue-800 text-white"
        )}
      >
        {children}
      </body>
    </html>
  );
}
